/**
 * Client-side PDF export for the trip expense tracker (jsPDF).
 * Simple report: branded header, totals summary, expenses grouped by day.
 */

import { jsPDF } from "jspdf";

const NAVY = [15, 27, 77];
const ORANGE = [249, 115, 22];
const GRAY = [100, 116, 139];
const DARK = [15, 23, 42];

const PAGE_MARGIN = 16;

/** Strip emoji / unsupported chars — Helvetica cannot render them */
function sanitize(text) {
  if (!text) return "";
  return String(text)
    .replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE00}-\u{FE0F}\u{200D}]/gu, "")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Format a number as "Rs 1,234" (jsPDF Helvetica can't render ₹) */
function money(amount) {
  return `Rs ${Number(amount || 0).toLocaleString("en-IN")}`;
}

/**
 * @param {object} opts
 * @param {string} opts.destination — trip destination for the title
 * @param {Array} opts.dayGroups — [{ label, dateLabel, total, items: [{ category, note, amount }] }]
 * @param {number} opts.totalSpent
 * @param {number|null} opts.budget
 */
export function downloadExpensesPdf({ destination, dayGroups, totalSpent, budget }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  let y = 0;

  // Branded header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Travora — Expense Report", PAGE_MARGIN, 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(sanitize(destination), PAGE_MARGIN, 19);
  y = 36;

  // Totals summary line
  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  const summary = budget
    ? `Total spent: ${money(totalSpent)}   |   Budget: ${money(budget)}   |   Left: ${money(Math.max(0, budget - totalSpent))}`
    : `Total spent: ${money(totalSpent)}`;
  doc.text(summary, PAGE_MARGIN, y);
  y += 10;

  // One section per day
  dayGroups.forEach((group) => {
    // New page if the section header would overflow
    if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 20;
    }

    // Day header with total on the right
    doc.setFillColor(241, 245, 249);
    doc.rect(PAGE_MARGIN, y - 5, contentWidth, 8, "F");
    doc.setTextColor(...NAVY);
    doc.setFontSize(10.5);
    doc.setFont("helvetica", "bold");
    doc.text(`${group.label}  ·  ${group.dateLabel}`, PAGE_MARGIN + 2, y);
    doc.setTextColor(...ORANGE);
    doc.text(money(group.total), pageWidth - PAGE_MARGIN - 2, y, { align: "right" });
    y += 9;

    // Expense rows
    group.items.forEach((item) => {
      if (y > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = 20;
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      const label = sanitize(item.note || item.category);
      doc.text(label.slice(0, 70), PAGE_MARGIN + 4, y);
      doc.setTextColor(...GRAY);
      doc.setFontSize(8.5);
      doc.text(sanitize(item.category), PAGE_MARGIN + 4, y + 4);
      doc.setTextColor(...DARK);
      doc.setFontSize(10);
      doc.text(money(item.amount), pageWidth - PAGE_MARGIN - 2, y, { align: "right" });
      y += 10;
    });

    y += 4;
  });

  // Footer with generation date
  doc.setTextColor(...GRAY);
  doc.setFontSize(8);
  doc.text(
    `Generated by Travora on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}`,
    PAGE_MARGIN,
    doc.internal.pageSize.getHeight() - 8
  );

  const base = sanitize(destination).replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 40);
  doc.save(`Travora-${base || "Trip"}-Expenses.pdf`);
}
